import { restList, restGet, restCreate, restUpdate, restDelete } from "./rest"

export const getCostSheets = (params?: Record<string, unknown>) => restList("costing", "CostSheet", params)
export const getCostSheet = (id: number) => restGet("costing", "CostSheet", id)
export const createCostSheet = (data: Record<string, unknown>) => restCreate("costing", "CostSheet", data)
export const updateCostSheet = (id: number, data: Record<string, unknown>) => restUpdate("costing", "CostSheet", id, data)
export const patchCostSheet = (id: number, data: Record<string, unknown>) => restUpdate("costing", "CostSheet", id, data)
export const deleteCostSheet = (id: number) => restDelete("costing", "CostSheet", id)
export const getPreCostings = (params?: Record<string, unknown>) => restList("costing", "PreCosting", params)
export const getPreCosting = (id: number) => restGet("costing", "PreCosting", id)
export const createPreCosting = (data: Record<string, unknown>) => restCreate("costing", "PreCosting", data)
export const updatePreCosting = (id: number, data: Record<string, unknown>) => restUpdate("costing", "PreCosting", id, data)
export const patchPreCosting = (id: number, data: Record<string, unknown>) => restUpdate("costing", "PreCosting", id, data)
export const deletePreCosting = (id: number) => restDelete("costing", "PreCosting", id)
export const getSmvRecords = (params?: Record<string, unknown>) => restList("merchandising", "SMVRecord", params)
export const getSmvRecord = (id: number) => restGet("merchandising", "SMVRecord", id)
export const createSmvRecord = (data: Record<string, unknown>) => restCreate("merchandising", "SMVRecord", data)
export const updateSmvRecord = (id: number, data: Record<string, unknown>) => restUpdate("merchandising", "SMVRecord", id, data)
export const patchSmvRecord = (id: number, data: Record<string, unknown>) => restUpdate("merchandising", "SMVRecord", id, data)
export const deleteSmvRecord = (id: number) => restDelete("merchandising", "SMVRecord", id)
