import { restList, restGet, restCreate, restUpdate, restDelete } from "./rest"

export const getBuyers = (params?: Record<string, unknown>) => restList("buyers", "Buyer", params)
export const getBuyer = (id: number) => restGet("buyers", "Buyer", id)
export const createBuyer = (data: Record<string, unknown>) => restCreate("buyers", "Buyer", data)
export const updateBuyer = (id: number, data: Record<string, unknown>) => restUpdate("buyers", "Buyer", id, data)
export const patchBuyer = (id: number, data: Record<string, unknown>) => restUpdate("buyers", "Buyer", id, data)
export const deleteBuyer = (id: number) => restDelete("buyers", "Buyer", id)
export const getBuyerCommunications = (params?: Record<string, unknown>) => restList("crm", "BuyerCommunication", params)
export const getBuyerCommunication = (id: number) => restGet("crm", "BuyerCommunication", id)
export const createBuyerCommunication = (data: Record<string, unknown>) => restCreate("crm", "BuyerCommunication", data)
export const getBuyerPortfolios = (params?: Record<string, unknown>) => restList("buyers", "BuyerPortfolio", params)
export const getBuyerPortfolio = (id: number) => restGet("buyers", "BuyerPortfolio", id)
export const getOrderAmendments = (params?: Record<string, unknown>) => restList("crm", "OrderAmendmentHistory", params)
export const getOrderAmendment = (id: number) => restGet("crm", "OrderAmendmentHistory", id)
export const getBuyerProfitabilities = (params?: Record<string, unknown>) => restList("crm", "BuyerProfitability", params)
export const getBuyerProfitability = (id: number) => restGet("crm", "BuyerProfitability", id)
export const getBuyerRatings = (params?: Record<string, unknown>) => restList("buyers", "BuyerRating", params)
export const getBuyerRating = (id: number) => restGet("buyers", "BuyerRating", id)
