import { restList, restGet, restCreate, restUpdate, restDelete } from "./rest"

export const getAssetCategories = (params?: Record<string, unknown>) => restList("fixed_assets", "AssetCategory", params)
export const getAssetCategory = (id: number) => restGet("fixed_assets", "AssetCategory", id)
export const createAssetCategory = (data: Record<string, unknown>) => restCreate("fixed_assets", "AssetCategory", data)
export const updateAssetCategory = (id: number, data: Record<string, unknown>) => restUpdate("fixed_assets", "AssetCategory", id, data)
export const patchAssetCategory = (id: number, data: Record<string, unknown>) => restUpdate("fixed_assets", "AssetCategory", id, data)
export const deleteAssetCategory = (id: number) => restDelete("fixed_assets", "AssetCategory", id)
export const getDepreciationSchedules = (params?: Record<string, unknown>) => restList("fixed_assets", "DepreciationSchedule", params)
export const getDepreciationSchedule = (id: number) => restGet("fixed_assets", "DepreciationSchedule", id)
export const createDepreciationSchedule = (data: Record<string, unknown>) => restCreate("fixed_assets", "DepreciationSchedule", data)
export const updateDepreciationSchedule = (id: number, data: Record<string, unknown>) => restUpdate("fixed_assets", "DepreciationSchedule", id, data)
export const patchDepreciationSchedule = (id: number, data: Record<string, unknown>) => restUpdate("fixed_assets", "DepreciationSchedule", id, data)
export const deleteDepreciationSchedule = (id: number) => restDelete("fixed_assets", "DepreciationSchedule", id)
export const getFixedAssets = (params?: Record<string, unknown>) => restList("fixed_assets", "FixedAsset", params)
export const getFixedAsset = (id: number) => restGet("fixed_assets", "FixedAsset", id)
export const createFixedAsset = (data: Record<string, unknown>) => restCreate("fixed_assets", "FixedAsset", data)
export const updateFixedAsset = (id: number, data: Record<string, unknown>) => restUpdate("fixed_assets", "FixedAsset", id, data)
export const patchFixedAsset = (id: number, data: Record<string, unknown>) => restUpdate("fixed_assets", "FixedAsset", id, data)
export const deleteFixedAsset = (id: number) => restDelete("fixed_assets", "FixedAsset", id)
