import { restList, restGet, restCreate, restUpdate, restDelete } from "./rest"

export const getAccessories = (params?: Record<string, unknown>) => restList("inventory", "Accessory", params)
export const getAccessory = (id: number) => restGet("inventory", "Accessory", id)
export const createAccessory = (data: Record<string, unknown>) => restCreate("inventory", "Accessory", data)
export const updateAccessory = (id: number, data: Record<string, unknown>) => restUpdate("inventory", "Accessory", id, data)
export const patchAccessory = (id: number, data: Record<string, unknown>) => restUpdate("inventory", "Accessory", id, data)
export const deleteAccessory = (id: number) => restDelete("inventory", "Accessory", id)
export const getFabrics = (params?: Record<string, unknown>) => restList("inventory", "Fabric", params)
export const getFabric = (id: number) => restGet("inventory", "Fabric", id)
export const createFabric = (data: Record<string, unknown>) => restCreate("inventory", "Fabric", data)
export const updateFabric = (id: number, data: Record<string, unknown>) => restUpdate("inventory", "Fabric", id, data)
export const patchFabric = (id: number, data: Record<string, unknown>) => restUpdate("inventory", "Fabric", id, data)
export const deleteFabric = (id: number) => restDelete("inventory", "Fabric", id)
export const getFabricInspections = (params?: Record<string, unknown>) => restList("quality", "FabricInspection", params)
export const getFabricInspection = (id: number) => restGet("quality", "FabricInspection", id)
export const createFabricInspection = (data: Record<string, unknown>) => restCreate("quality", "FabricInspection", data)
export const updateFabricInspection = (id: number, data: Record<string, unknown>) => restUpdate("quality", "FabricInspection", id, data)
export const patchFabricInspection = (id: number, data: Record<string, unknown>) => restUpdate("quality", "FabricInspection", id, data)
export const deleteFabricInspection = (id: number) => restDelete("quality", "FabricInspection", id)
export const getFloorRequisitions = (params?: Record<string, unknown>) => restList("production", "FloorRequisition", params)
export const getFloorRequisition = (id: number) => restGet("production", "FloorRequisition", id)
export const createFloorRequisition = (data: Record<string, unknown>) => restCreate("production", "FloorRequisition", data)
export const updateFloorRequisition = (id: number, data: Record<string, unknown>) => restUpdate("production", "FloorRequisition", id, data)
export const patchFloorRequisition = (id: number, data: Record<string, unknown>) => restUpdate("production", "FloorRequisition", id, data)
export const deleteFloorRequisition = (id: number) => restDelete("production", "FloorRequisition", id)
export const getPhysicalInventories = (params?: Record<string, unknown>) => restList("inventory", "PhysicalInventory", params)
export const getPhysicalInventory = (id: number) => restGet("inventory", "PhysicalInventory", id)
export const createPhysicalInventory = (data: Record<string, unknown>) => restCreate("inventory", "PhysicalInventory", data)
export const updatePhysicalInventory = (id: number, data: Record<string, unknown>) => restUpdate("inventory", "PhysicalInventory", id, data)
export const patchPhysicalInventory = (id: number, data: Record<string, unknown>) => restUpdate("inventory", "PhysicalInventory", id, data)
export const deletePhysicalInventory = (id: number) => restDelete("inventory", "PhysicalInventory", id)
export const getRmBookings = (params?: Record<string, unknown>) => restList("procurement", "RawMaterialBooking", params)
export const getRmBooking = (id: number) => restGet("procurement", "RawMaterialBooking", id)
export const createRmBooking = (data: Record<string, unknown>) => restCreate("procurement", "RawMaterialBooking", data)
export const updateRmBooking = (id: number, data: Record<string, unknown>) => restUpdate("procurement", "RawMaterialBooking", id, data)
export const patchRmBooking = (id: number, data: Record<string, unknown>) => restUpdate("procurement", "RawMaterialBooking", id, data)
export const deleteRmBooking = (id: number) => restDelete("procurement", "RawMaterialBooking", id)
export const getRmRequisitions = (params?: Record<string, unknown>) => restList("procurement", "RawMaterialRequisition", params)
export const getRmRequisition = (id: number) => restGet("procurement", "RawMaterialRequisition", id)
export const createRmRequisition = (data: Record<string, unknown>) => restCreate("procurement", "RawMaterialRequisition", data)
export const updateRmRequisition = (id: number, data: Record<string, unknown>) => restUpdate("procurement", "RawMaterialRequisition", id, data)
export const patchRmRequisition = (id: number, data: Record<string, unknown>) => restUpdate("procurement", "RawMaterialRequisition", id, data)
export const deleteRmRequisition = (id: number) => restDelete("procurement", "RawMaterialRequisition", id)
export const getStockMovements = (params?: Record<string, unknown>) => restList("inventory", "StockMovement", params)
export const getStockMovement = (id: number) => restGet("inventory", "StockMovement", id)
export const createStockMovement = (data: Record<string, unknown>) => restCreate("inventory", "StockMovement", data)
export const updateStockMovement = (id: number, data: Record<string, unknown>) => restUpdate("inventory", "StockMovement", id, data)
export const patchStockMovement = (id: number, data: Record<string, unknown>) => restUpdate("inventory", "StockMovement", id, data)
export const deleteStockMovement = (id: number) => restDelete("inventory", "StockMovement", id)
export const getTrims = (params?: Record<string, unknown>) => restList("inventory", "Trim", params)
export const getTrim = (id: number) => restGet("inventory", "Trim", id)
export const createTrim = (data: Record<string, unknown>) => restCreate("inventory", "Trim", data)
export const updateTrim = (id: number, data: Record<string, unknown>) => restUpdate("inventory", "Trim", id, data)
export const patchTrim = (id: number, data: Record<string, unknown>) => restUpdate("inventory", "Trim", id, data)
export const deleteTrim = (id: number) => restDelete("inventory", "Trim", id)
export const getWarehouses = (params?: Record<string, unknown>) => restList("inventory", "Warehouse", params)
export const getWarehouse = (id: number) => restGet("inventory", "Warehouse", id)
export const createWarehouse = (data: Record<string, unknown>) => restCreate("inventory", "Warehouse", data)
export const updateWarehouse = (id: number, data: Record<string, unknown>) => restUpdate("inventory", "Warehouse", id, data)
export const patchWarehouse = (id: number, data: Record<string, unknown>) => restUpdate("inventory", "Warehouse", id, data)
export const deleteWarehouse = (id: number) => restDelete("inventory", "Warehouse", id)
