import { restList, restGet, restCreate, restUpdate, restDelete } from "./rest"

export const getOrders = (params?: Record<string, unknown>) => restList("orders", "Order", params)
export const getOrder = (id: number) => restGet("orders", "Order", id)
export const createOrder = (data: Record<string, unknown>) => restCreate("orders", "Order", data)
export const updateOrder = (id: number, data: Record<string, unknown>) => restUpdate("orders", "Order", id, data)
export const patchOrder = (id: number, data: Record<string, unknown>) => restUpdate("orders", "Order", id, data)
export const deleteOrder = (id: number) => restDelete("orders", "Order", id)
export const getOrderAmendments = (params?: Record<string, unknown>) => restList("crm", "OrderAmendmentHistory", params)
export const getOrderAmendment = (id: number) => restGet("crm", "OrderAmendmentHistory", id)
export const createOrderAmendment = (data: Record<string, unknown>) => restCreate("crm", "OrderAmendmentHistory", data)
export const updateOrderAmendment = (id: number, data: Record<string, unknown>) => restUpdate("crm", "OrderAmendmentHistory", id, data)
export const patchOrderAmendment = (id: number, data: Record<string, unknown>) => restUpdate("crm", "OrderAmendmentHistory", id, data)
export const deleteOrderAmendment = (id: number) => restDelete("crm", "OrderAmendmentHistory", id)
export const getSampleOrders = (params?: Record<string, unknown>) => restList("merchandising", "SampleOrder", params)
export const getSampleOrder = (id: number) => restGet("merchandising", "SampleOrder", id)
export const createSampleOrder = (data: Record<string, unknown>) => restCreate("merchandising", "SampleOrder", data)
export const updateSampleOrder = (id: number, data: Record<string, unknown>) => restUpdate("merchandising", "SampleOrder", id, data)
export const patchSampleOrder = (id: number, data: Record<string, unknown>) => restUpdate("merchandising", "SampleOrder", id, data)
export const deleteSampleOrder = (id: number) => restDelete("merchandising", "SampleOrder", id)
export const getShipments = (params?: Record<string, unknown>) => restList("commercial", "Shipment", params)
export const getShipment = (id: number) => restGet("commercial", "Shipment", id)
export const createShipment = (data: Record<string, unknown>) => restCreate("commercial", "Shipment", data)
export const updateShipment = (id: number, data: Record<string, unknown>) => restUpdate("commercial", "Shipment", id, data)
export const patchShipment = (id: number, data: Record<string, unknown>) => restUpdate("commercial", "Shipment", id, data)
export const deleteShipment = (id: number) => restDelete("commercial", "Shipment", id)
