import { restList, restGet, restCreate, restUpdate, restDelete } from "./rest"

export const getPurchaseOrders = (params?: Record<string, unknown>) => restList("merchandising", "PurchaseOrder", params)
export const getPurchaseOrder = (id: number) => restGet("merchandising", "PurchaseOrder", id)
export const createPurchaseOrder = (data: Record<string, unknown>) => restCreate("merchandising", "PurchaseOrder", data)
export const updatePurchaseOrder = (id: number, data: Record<string, unknown>) => restUpdate("merchandising", "PurchaseOrder", id, data)
export const patchPurchaseOrder = (id: number, data: Record<string, unknown>) => restUpdate("merchandising", "PurchaseOrder", id, data)
export const deletePurchaseOrder = (id: number) => restDelete("merchandising", "PurchaseOrder", id)
export const getQuotationAnalyses = (params?: Record<string, unknown>) => restList("procurement", "QuotationAnalysis", params)
export const getQuotationAnalysis = (id: number) => restGet("procurement", "QuotationAnalysis", id)
export const createQuotationAnalysis = (data: Record<string, unknown>) => restCreate("procurement", "QuotationAnalysis", data)
export const updateQuotationAnalysis = (id: number, data: Record<string, unknown>) => restUpdate("procurement", "QuotationAnalysis", id, data)
export const patchQuotationAnalysis = (id: number, data: Record<string, unknown>) => restUpdate("procurement", "QuotationAnalysis", id, data)
export const deleteQuotationAnalysis = (id: number) => restDelete("procurement", "QuotationAnalysis", id)
export const getSuppliers = (params?: Record<string, unknown>) => restList("procurement", "Supplier", params)
export const getSupplier = (id: number) => restGet("procurement", "Supplier", id)
export const createSupplier = (data: Record<string, unknown>) => restCreate("procurement", "Supplier", data)
export const updateSupplier = (id: number, data: Record<string, unknown>) => restUpdate("procurement", "Supplier", id, data)
export const patchSupplier = (id: number, data: Record<string, unknown>) => restUpdate("procurement", "Supplier", id, data)
export const deleteSupplier = (id: number) => restDelete("procurement", "Supplier", id)
