import { restList, restGet, restCreate, restUpdate, restDelete } from "./rest"

export const getCapacityBookings = (params?: Record<string, unknown>) => restList("ie_planning", "CapacityBooking", params)
export const getCapacityBooking = (id: number) => restGet("ie_planning", "CapacityBooking", id)
export const createCapacityBooking = (data: Record<string, unknown>) => restCreate("ie_planning", "CapacityBooking", data)
export const updateCapacityBooking = (id: number, data: Record<string, unknown>) => restUpdate("ie_planning", "CapacityBooking", id, data)
export const patchCapacityBooking = (id: number, data: Record<string, unknown>) => restUpdate("ie_planning", "CapacityBooking", id, data)
export const deleteCapacityBooking = (id: number) => restDelete("ie_planning", "CapacityBooking", id)
export const getCuttingRecords = (params?: Record<string, unknown>) => restList("production", "CuttingRecord", params)
export const getCuttingRecord = (id: number) => restGet("production", "CuttingRecord", id)
export const createCuttingRecord = (data: Record<string, unknown>) => restCreate("production", "CuttingRecord", data)
export const updateCuttingRecord = (id: number, data: Record<string, unknown>) => restUpdate("production", "CuttingRecord", id, data)
export const patchCuttingRecord = (id: number, data: Record<string, unknown>) => restUpdate("production", "CuttingRecord", id, data)
export const deleteCuttingRecord = (id: number) => restDelete("production", "CuttingRecord", id)
export const getJobOrders = (params?: Record<string, unknown>) => restList("tna", "JobOrder", params)
export const getJobOrder = (id: number) => restGet("tna", "JobOrder", id)
export const createJobOrder = (data: Record<string, unknown>) => restCreate("tna", "JobOrder", data)
export const updateJobOrder = (id: number, data: Record<string, unknown>) => restUpdate("tna", "JobOrder", id, data)
export const patchJobOrder = (id: number, data: Record<string, unknown>) => restUpdate("tna", "JobOrder", id, data)
export const deleteJobOrder = (id: number) => restDelete("tna", "JobOrder", id)
export const getLinePlans = (params?: Record<string, unknown>) => restList("ie_planning", "LinePlan", params)
export const getLinePlan = (id: number) => restGet("ie_planning", "LinePlan", id)
export const createLinePlan = (data: Record<string, unknown>) => restCreate("ie_planning", "LinePlan", data)
export const updateLinePlan = (id: number, data: Record<string, unknown>) => restUpdate("ie_planning", "LinePlan", id, data)
export const patchLinePlan = (id: number, data: Record<string, unknown>) => restUpdate("ie_planning", "LinePlan", id, data)
export const deleteLinePlan = (id: number) => restDelete("ie_planning", "LinePlan", id)
export const getProductionLines = (params?: Record<string, unknown>) => restList("production", "ProductionLine", params)
export const getProductionLine = (id: number) => restGet("production", "ProductionLine", id)
export const createProductionLine = (data: Record<string, unknown>) => restCreate("production", "ProductionLine", data)
export const updateProductionLine = (id: number, data: Record<string, unknown>) => restUpdate("production", "ProductionLine", id, data)
export const patchProductionLine = (id: number, data: Record<string, unknown>) => restUpdate("production", "ProductionLine", id, data)
export const deleteProductionLine = (id: number) => restDelete("production", "ProductionLine", id)
export const getProductionOrders = (params?: Record<string, unknown>) => restList("production", "ProductionOrder", params)
export const getProductionOrder = (id: number) => restGet("production", "ProductionOrder", id)
export const createProductionOrder = (data: Record<string, unknown>) => restCreate("production", "ProductionOrder", data)
export const updateProductionOrder = (id: number, data: Record<string, unknown>) => restUpdate("production", "ProductionOrder", id, data)
export const patchProductionOrder = (id: number, data: Record<string, unknown>) => restUpdate("production", "ProductionOrder", id, data)
export const deleteProductionOrder = (id: number) => restDelete("production", "ProductionOrder", id)
export const getProductionPlans = (params?: Record<string, unknown>) => restList("ie_planning", "ProductionPlan", params)
export const getProductionPlan = (id: number) => restGet("ie_planning", "ProductionPlan", id)
export const createProductionPlan = (data: Record<string, unknown>) => restCreate("ie_planning", "ProductionPlan", data)
export const updateProductionPlan = (id: number, data: Record<string, unknown>) => restUpdate("ie_planning", "ProductionPlan", id, data)
export const patchProductionPlan = (id: number, data: Record<string, unknown>) => restUpdate("ie_planning", "ProductionPlan", id, data)
export const deleteProductionPlan = (id: number) => restDelete("ie_planning", "ProductionPlan", id)
export const getSewingRecords = (params?: Record<string, unknown>) => restList("production", "SewingRecord", params)
export const getSewingRecord = (id: number) => restGet("production", "SewingRecord", id)
export const createSewingRecord = (data: Record<string, unknown>) => restCreate("production", "SewingRecord", data)
export const updateSewingRecord = (id: number, data: Record<string, unknown>) => restUpdate("production", "SewingRecord", id, data)
export const patchSewingRecord = (id: number, data: Record<string, unknown>) => restUpdate("production", "SewingRecord", id, data)
export const deleteSewingRecord = (id: number) => restDelete("production", "SewingRecord", id)
export const getDevelopmentMonitoring = (params?: Record<string, unknown>) => restList("merchandising", "DevelopmentMonitoring", params)
export const getDevelopmentMonitor = (id: number) => restGet("merchandising", "DevelopmentMonitoring", id)
export const createDevelopmentMonitor = (data: Record<string, unknown>) => restCreate("merchandising", "DevelopmentMonitoring", data)
export const updateDevelopmentMonitor = (id: number, data: Record<string, unknown>) => restUpdate("merchandising", "DevelopmentMonitoring", id, data)
export const patchDevelopmentMonitor = (id: number, data: Record<string, unknown>) => restUpdate("merchandising", "DevelopmentMonitoring", id, data)
export const deleteDevelopmentMonitor = (id: number) => restDelete("merchandising", "DevelopmentMonitoring", id)
export const getPlans = (params?: Record<string, unknown>) => restList("planning", "Plan", params)
export const getPlan = (id: number) => restGet("planning", "Plan", id)
export const createPlan = (data: Record<string, unknown>) => restCreate("planning", "Plan", data)
export const updatePlan = (id: number, data: Record<string, unknown>) => restUpdate("planning", "Plan", id, data)
export const patchPlan = (id: number, data: Record<string, unknown>) => restUpdate("planning", "Plan", id, data)
export const deletePlan = (id: number) => restDelete("planning", "Plan", id)
