import { restList, restGet, restCreate, restUpdate, restDelete } from "./rest"

export const getDefectCategories = (params?: Record<string, unknown>) => restList("quality", "DefectCategory", params)
export const getDefectCategory = (id: number) => restGet("quality", "DefectCategory", id)
export const createDefectCategory = (data: Record<string, unknown>) => restCreate("quality", "DefectCategory", data)
export const updateDefectCategory = (id: number, data: Record<string, unknown>) => restUpdate("quality", "DefectCategory", id, data)
export const patchDefectCategory = (id: number, data: Record<string, unknown>) => restUpdate("quality", "DefectCategory", id, data)
export const deleteDefectCategory = (id: number) => restDelete("quality", "DefectCategory", id)
export const getEndlineQc = (params?: Record<string, unknown>) => restList("quality", "EndLineQC", params)
export const getEndlineQcRecord = (id: number) => restGet("quality", "EndLineQC", id)
export const createEndlineQc = (data: Record<string, unknown>) => restCreate("quality", "EndLineQC", data)
export const updateEndlineQc = (id: number, data: Record<string, unknown>) => restUpdate("quality", "EndLineQC", id, data)
export const patchEndlineQc = (id: number, data: Record<string, unknown>) => restUpdate("quality", "EndLineQC", id, data)
export const deleteEndlineQc = (id: number) => restDelete("quality", "EndLineQC", id)
export const getFinalInspections = (params?: Record<string, unknown>) => restList("quality", "FinalInspection", params)
export const getFinalInspection = (id: number) => restGet("quality", "FinalInspection", id)
export const createFinalInspection = (data: Record<string, unknown>) => restCreate("quality", "FinalInspection", data)
export const updateFinalInspection = (id: number, data: Record<string, unknown>) => restUpdate("quality", "FinalInspection", id, data)
export const patchFinalInspection = (id: number, data: Record<string, unknown>) => restUpdate("quality", "FinalInspection", id, data)
export const deleteFinalInspection = (id: number) => restDelete("quality", "FinalInspection", id)
export const getInlineQc = (params?: Record<string, unknown>) => restList("quality", "InlineQC", params)
export const getInlineQcRecord = (id: number) => restGet("quality", "InlineQC", id)
export const createInlineQc = (data: Record<string, unknown>) => restCreate("quality", "InlineQC", data)
export const updateInlineQc = (id: number, data: Record<string, unknown>) => restUpdate("quality", "InlineQC", id, data)
export const patchInlineQc = (id: number, data: Record<string, unknown>) => restUpdate("quality", "InlineQC", id, data)
export const deleteInlineQc = (id: number) => restDelete("quality", "InlineQC", id)
export const getInspectionPacking = (params?: Record<string, unknown>) => restList("production", "InspectionPacking", params)
export const getInspectionPackingRecord = (id: number) => restGet("production", "InspectionPacking", id)
export const createInspectionPacking = (data: Record<string, unknown>) => restCreate("production", "InspectionPacking", data)
export const updateInspectionPacking = (id: number, data: Record<string, unknown>) => restUpdate("production", "InspectionPacking", id, data)
export const patchInspectionPacking = (id: number, data: Record<string, unknown>) => restUpdate("production", "InspectionPacking", id, data)
export const deleteInspectionPacking = (id: number) => restDelete("production", "InspectionPacking", id)
export const getRejectionReports = (params?: Record<string, unknown>) => restList("quality", "RejectionReport", params)
export const getRejectionReport = (id: number) => restGet("quality", "RejectionReport", id)
export const createRejectionReport = (data: Record<string, unknown>) => restCreate("quality", "RejectionReport", data)
export const updateRejectionReport = (id: number, data: Record<string, unknown>) => restUpdate("quality", "RejectionReport", id, data)
export const patchRejectionReport = (id: number, data: Record<string, unknown>) => restUpdate("quality", "RejectionReport", id, data)
export const deleteRejectionReport = (id: number) => restDelete("quality", "RejectionReport", id)
