import { restList, restGet, restCreate, restUpdate, restDelete } from "./rest"

export const getAlarmNotifications = (params?: Record<string, unknown>) => restList("tna", "AlarmNotification", params)
export const getAlarmNotification = (id: number) => restGet("tna", "AlarmNotification", id)
export const getSchedules = (params?: Record<string, unknown>) => restList("scheduling", "Schedule", params)
export const getSchedule = (id: number) => restGet("scheduling", "Schedule", id)
export const createSchedule = (data: Record<string, unknown>) => restCreate("scheduling", "Schedule", data)
export const updateSchedule = (id: number, data: Record<string, unknown>) => restUpdate("scheduling", "Schedule", id, data)
export const patchSchedule = (id: number, data: Record<string, unknown>) => restUpdate("scheduling", "Schedule", id, data)
export const deleteSchedule = (id: number) => restDelete("scheduling", "Schedule", id)
export const getTasks = (params?: Record<string, unknown>) => restList("tna", "Task", params)
export const getTask = (id: number) => restGet("tna", "Task", id)
export const createTask = (data: Record<string, unknown>) => restCreate("tna", "Task", data)
export const updateTask = (id: number, data: Record<string, unknown>) => restUpdate("tna", "Task", id, data)
export const patchTask = (id: number, data: Record<string, unknown>) => restUpdate("tna", "Task", id, data)
export const deleteTask = (id: number) => restDelete("tna", "Task", id)
export const getTimelines = (params?: Record<string, unknown>) => restList("tna", "Timeline", params)
export const getTimeline = (id: number) => restGet("tna", "Timeline", id)
export const createTimeline = (data: Record<string, unknown>) => restCreate("tna", "Timeline", data)
export const updateTimeline = (id: number, data: Record<string, unknown>) => restUpdate("tna", "Timeline", id, data)
export const patchTimeline = (id: number, data: Record<string, unknown>) => restUpdate("tna", "Timeline", id, data)
export const deleteTimeline = (id: number) => restDelete("tna", "Timeline", id)
